project_name: vendor_invoice
vendor_name: bktw
template_version: v_00_01
image_size: [3400, 4395]
line_height: 30
header:
  - label: Date of Registration
    field: date_of_registration
    boundingbox: [1500, 670, 2400, 780]
    pattern: 'DATE ?:? ?(.*)'
    format: 
      type: DATE
      regex: ['%b%d%Y']
  - label: Advising Bank
    field: advising_bank
    boundingbox: [880, 209, 2500, 350]
  - label: OUR REF
    field: advising_no_of_bank
    boundingbox: [460, 800, 1100, 890]
  - label: 'LETTER OF CREDIT NO'
    field: 'lc_no'
    boundingbox: [1380, 800, 2300, 910]
  - label: L/C Received from
    field: issuing_bank
    boundingbox: [1380, 880, 2500, 1040]
  - label: Applicant
    field: applicant
    boundingbox: []
  - label: AMOUNT
    field: amount
    boundingbox: []
  - label: EXPIRY DATE
    field: expiry_date
    boundingbox: []
main_body:
  - label: Page 0
    field: page_0
    index: 0
    boundingbox: [0, 1530, 3080, 3590]
  - label: Page N
    field: page_n
    index: n
    boundingbox: [0, 500, 3080, 3700]
swift_regex: ': ?(\d{2}[A-Z]?) ?:' # used to get swift code
swift_content: ': ?\d{2}[A-Z]? ?: ?.*\n' # used to get swift content 
