project_name: vendor_invoice
vendor_name: chartered
template_version: v_00_01
image_size: [3306, 4676]
line_height: 30
header:
  - label: Date of Registration
    field: date_of_registration
    boundingbox: [1880, 1010, 2320, 1072]
    pattern: 'DATE ?:? ?(.*)'
    format: 
      type: DATE
      regex: ['%d%b%y']
  - label: Advising Bank
    field: advising_bank
    boundingbox: [2600, 220, 3060, 430]
  - label: OUR REF
    field: advising_no_of_bank
    boundingbox: [2190, 680, 2830, 780]
  - label: 'LETTER OF CREDIT NO'
    field: 'lc_no'
    boundingbox: [2190, 800, 2830, 930]
  - label: L/C Received from
    field: issuing_bank
    boundingbox: [1130, 1270, 2710, 1410]
  - label: Applicant
    field: applicant
    boundingbox: [1040, 1430, 2760, 1540]
  - label: AMOUNT
    field: amount
    boundingbox: [1850, 1150, 2630, 1250]
  - label: EXPIRY DATE
    field: expiry_date
    boundingbox: []
main_body:
  - label: Page N
    field: page_n
    index: n
    boundingbox: [560, 760, 2880, 3310]
swift_regex: ': ?(\d{2}[A-Z]?) ?:' # used to get swift code
swift_content: ': ?\d{2}[A-Z]? ?: ?.*\n' # used to get swift content 
