project_name: vendor_invoice
vendor_name: citi
template_version: v_00_01
image_size: [3306, 4676]
line_height: 30
header:
  - label: Date of Registration
    field: date_of_registration
    boundingbox: [260, 800, 940, 920]
    pattern: 'DATE ?:? ?(.*)'
    format: 
      type: DATE
      regex: ['%b%d%Y']
  - label: Advising Bank
    field: advising_bank
    boundingbox: [1800, 1140, 3030, 1580]
    pattern: 'FROM ?:?[ \n]?([.\s\S]*)'
  - label: Field Group
    field: field_group
    boundingbox: [200, 1540, 1860, 2160]
    line_height: 30
    readby: byline
    item_list:
      # use the advising number at the end of first page
      - label: 'OUR REF'
        field: 'advising_no_of_bank' 
      - label: 'LETTER OF CREDIT NO'
        field: 'lc_no'
      - label: 'OPENED BY'
        field: 'issuing_bank'
      - label: 'BY ORDER OF'
        field: 'applicant'
      - label: 'AMOUNT'
        field: 'amount'
      - label: 'EXPIRY DATE'
        field: 'expiry_date'
  - label: OUR REF
    field: advising_no_of_bank
    boundingbox: [220, 4240, 1130, 4360]
main_body:
  - label: Page 0
    field: page_0
    index: 0
    boundingbox: [180, 2168, 3222, 4248]
  - label: Page N
    field: page_n
    index: n
    boundingbox: [180, 430, 3206, 4250]
swift_regex: ':?: ?(\d{2} ?[A-Z]?) ?:'  # used to get swift code
swift_content: ':?: ?\d{2} ?[A-Z]? ?: ?\(.*[\)J] ?\n?' # used to get swift content 
