project_name: vendor_invoice
vendor_name: huanan
template_version: v_00_01
image_size: [1653, 2338]
line_height: 20
header:
  - label: Date of Registration
    field: date_of_registration
    boundingbox: [1160,460,1400,510]
    pattern: 'DATE ?:? ?(.*)'
    format: 
      type: DATE
      regex: ['%Y/%m/%d']
  - label: Advising Bank
    field: advising_bank
    boundingbox: [406,235,1325,295]
  - label: L/C Received from
    field: issuing_bank
    boundingbox: [210,690,990,845]
  - label: OUR REF
    field: advising_no_of_bank
    boundingbox: [1305,505,1545,550]
  - label: AMOUNT
    field: amount
    boundingbox: [1190,630,1595,680]
main_body:
  - label: Page 0
    field: page_0
    index: 0
    boundingbox: [5,850,1650,2230]
  - label: Page 1
    field: page_1
    index: 1
    boundingbox: [5,800,1650,2230]
  - label: Page N
    field: page_n
    index: n
    boundingbox: [5,500,1650,2230]
swift_regex: '\*?(\d{1,2}.? +[A-Z]?) ?:'
swift_end_regx: '- - - - -'
swift_content: '\*?\d{1,2}.? +[A-Z]? ?:'