project_name: vendor_invoice
vendor_name: megga
template_version: v_00_01
image_size: [1653, 2338]
line_height: 30
header:
  - label: Date of Registration
    field: date_of_registration
    boundingbox: [810,205,1125,255]
    format: 
      type: DATE
      regex: ['%b%d%Y']
  - label: Advising Bank
    field: advising_bank
    boundingbox: [445, 15, 1280, 70]
  - label: OUR REF
    field: advising_no_of_bank
    boundingbox: [817,285,1260,330]
  - label: 'LETTER OF CREDIT NO'
    field: 'lc_no'
    boundingbox: []
  - label: L/C Received from
    field: issuing_bank
    boundingbox: [16, 528, 1245, 580]
    pattern: 'message from *([.\s\S]*)'
  - label: Applicant
    field: applicant
    boundingbox: []
  - label: AMOUNT
    field: amount
    boundingbox: []
  - label: EXPIRY DATE
    field: expiry_date
    boundingbox: []
main_body:
  - label: Page 0
    field: page_0
    index: 0
    boundingbox: [10,980,1630,1960]
  - label: Page N
    field: page_n
    index: n
    boundingbox: [10,450,1630,1960]
swift_regex: ' ?(\d{2} ?[A-Z]?) ?:'
swift_content: ' ?\d{2} ?[A-Z]? ?: ?.*\n'