project_name: vendor_invoice
vendor_name: megga
template_version: v_00_01
image_size: [3306, 4676]
line_height: 30
header:
  - label: Date of Registration
    field: date_of_registration
    boundingbox: [1620, 410, 2250, 510]
    format: 
      type: DATE
      regex: ['%b%d%Y']
  - label: Advising Bank
    field: advising_bank
    boundingbox: [890, 30, 2560, 140]
  - label: OUR REF
    field: advising_no_of_bank
    boundingbox: [1634, 570, 2520, 660]
  - label: 'LETTER OF CREDIT NO'
    field: 'lc_no'
    boundingbox: []
  - label: L/C Received from
    field: issuing_bank
    boundingbox: [32, 800, 3200, 1230]
    pattern: 'message from *([^\(]*)'
  - label: Applicant
    field: applicant
    boundingbox: []
  - label: AMOUNT
    field: amount
    boundingbox: []
  - label: EXPIRY DATE
    field: expiry_date
    boundingbox: []
main_body:
  - label: Page 0
    field: page_0
    index: 0
    boundingbox: [20, 1960, 3260, 3880]
  - label: Page N
    field: page_n
    index: n
    boundingbox: [20, 860, 3260, 3880]
swift_regex: ':? ?(\D\d{2} ?[A-Z4]?) ?:'
swift_content: ':? ?\D\d{2} ?[A-Z4]? ?: ?.*\n'